language: node_js

notifications:
  email: false

node_js:
  - "10.15.3"

services:
  - mongodb

before_install:
- openssl aes-256-cbc -K $encrypted_994543d654b9_key -iv $encrypted_994543d654b9_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d

before_script:
  - sleep 10
  - mongo calendz --eval 'db.createUser({user:"username",pwd:"password",roles:["readWrite"]});'

install: npm install

jobs:
  include:
    - stage: Tests
      script: 
        - npm run lint
        - npm run test:mock
        - npm run test:coverage
        - npm run test:coveralls
    - stage: Build Docker image
      if: branch = feature/continuous-deployment
      script:
      - "PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
      - echo "==== Building calendz/api:$PACKAGE_VERSION ===="
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t calendz/api .
      - docker images
      - docker tag calendz/api calendz/api:latest
      - docker tag calendz/api calendz/api:${PACKAGE_VERSION}
      - docker push calendz/api:latest
      - docker push calendz/api:${PACKAGE_VERSION}
    - stage: Deploy
      if: branch = feature/continuous-deployment
      script:
        - sh .travis/deploy.sh

after_success:
  - wget https://raw.githubusercontent.com/calendz/travis-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/calendz/travis-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL

cache:
  directories:
    - node_modules